import { pinSlots } from './_pin-lib.mjs';

await pinSlots('laundry', [
  {
    rank: 1,
    label: 'Mesh Laundry Bags',
    queries: ['mesh laundry bags delicates set', 'lingerie mesh wash bags 3 pack', 'mesh laundry wash bags zipper'],
    maxPrice: 20,
    must: [/mesh|laundry.?bag|wash.?bag/i],
    prefer: [/mesh|laundry|delicates|wash.?bag/i],
    exclude: [/hamper.?only|basket.?only/i],
  },
  {
    rank: 2,
    label: 'Wool Dryer Balls',
    queries: ['wool dryer balls XL 6 pack', 'smart sheep wool dryer balls', 'wool dryer balls organic'],
    maxPrice: 25,
    must: [/dryer.?ball/i],
    prefer: [/wool|dryer.?ball/i],
    exclude: [/plastic.?ball|scent.?bead/i],
  },
  {
    rank: 3,
    label: 'Laundry Hamper',
    queries: ['collapsible laundry hamper tall', 'laundry basket with handles freestanding', 'tall laundry hamper bathroom'],
    maxPrice: 40,
    must: [/hamper|laundry.?basket/i],
    prefer: [/hamper|laundry.?basket|collapsible/i],
    exclude: [/bag.?only.?drawstring.?small/i],
  },
  {
    rank: 4,
    label: 'Stain Remover Pen',
    queries: ['Tide to Go stain remover pen', 'stain remover pen laundry travel', 'instant stain remover pen pack'],
    maxPrice: 15,
    must: [/stain/i],
    prefer: [/stain.?remover|tide.?to.?go|pen/i],
    exclude: [/bleach.?only|oxy.?big.?tub/i],
  },
  {
    rank: 5,
    label: 'Folding Board',
    queries: ['shirt folding board laundry', 'clothes folding board adult', 'tshirt folding board tool'],
    maxPrice: 20,
    must: [/fold/i],
    prefer: [/folding.?board|shirt.?fold|clothes.?fold/i],
    exclude: [/ironing.?board/i],
  },
  {
    rank: 6,
    label: 'Drying Rack',
    queries: ['collapsible clothes drying rack freestanding', 'laundry drying rack foldable', 'clothes air dryer rack indoor'],
    maxPrice: 45,
    must: [/drying.?rack|clothes.?rack|air.?dry/i],
    prefer: [/drying.?rack|foldable|collapsible/i],
    exclude: [/dish.?rack|bike.?rack/i],
  },
  {
    rank: 7,
    label: 'Lint Remover',
    queries: ['fabric shaver lint remover rechargeable', 'sweater shaver lint remover', 'electric lint remover clothes'],
    maxPrice: 25,
    must: [/lint|fabric.?shaver|sweater.?shaver/i],
    prefer: [/lint.?remover|fabric.?shaver/i],
    exclude: [/roller.?only.?sticky.?tape.?huge.?pack.?only/i],
  },
  {
    rank: 8,
    label: 'Laundry Detergent Sheets',
    queries: ['laundry detergent sheets earth breeze', 'eco laundry sheets detergent', 'detergent sheets fragrance free'],
    maxPrice: 30,
    must: [/detergent.?sheet|laundry.?sheet/i],
    prefer: [/detergent.?sheet|laundry.?sheet|earth.?breeze/i],
    exclude: [/dryer.?sheet.?only|fabric.?softener.?only/i],
  },
  {
    rank: 9,
    label: 'Ironing Board Cover',
    queries: ['ironing board cover scorched resistant', 'thick ironing board cover pad', 'ironing board cover with pad'],
    maxPrice: 25,
    must: [/ironing.?board.?cover|iron.?board.?cover/i],
    prefer: [/ironing.?board.?cover|scorch|pad/i],
    exclude: [/ironing.?board.?full/i],
  },
  {
    rank: 10,
    label: 'Clothespins / Clips',
    queries: ['clothespins stainless steel pack', 'clothes pins laundry clips durable', 'plastic clothespins pack of 50'],
    maxPrice: 15,
    must: [/clothes.?pin|clothespin|clothes.?clip/i],
    prefer: [/clothespin|clothes.?pin|clip/i],
    exclude: [/chip.?clip.?kitchen.?only/i],
  },
]);
