import { pinSlots } from './_pin-lib.mjs';

await pinSlots('drawer', [
  { rank: 1, label: 'Expandable Dividers', queries: ['expandable drawer dividers adjustable', 'drawer organizer dividers bamboo', 'adjustable drawer divider set'], maxPrice: 30, must: [/drawer/i], prefer: [/drawer.?divider|expandable|adjustable/i], exclude: [/file.?cabinet/i] },
  { rank: 2, label: 'Utensil Tray', queries: ['kitchen drawer organizer utensils adjustable', 'utensil drawer organizer expandable', 'silverware drawer organizer bamboo'], maxPrice: 35, must: [/utensil|silverware|drawer/i], prefer: [/utensil|silverware|drawer.?organizer/i], exclude: [/utensil.?set.?only/i] },
  { rank: 3, label: 'Spice Drawer Insert', queries: ['spice drawer organizer insert tiered', 'in drawer spice rack organizer', 'spice drawer organizer labels'], maxPrice: 35, must: [/spice|drawer/i], prefer: [/spice.?drawer|spice.?organizer/i], exclude: [/spice.?rack.?wall.?only/i] },
  { rank: 4, label: 'Junk Drawer Tray', queries: ['junk drawer organizer trays modular', 'modular drawer organizer bins set', 'interlocking drawer organizer trays'], maxPrice: 25, must: [/drawer|organizer|tray|bin/i], prefer: [/drawer.?organizer|modular|interlocking/i], exclude: [/desk.?tray.?paper/i] },
  { rank: 5, label: 'Cutlery Tray', queries: ['cutlery tray drawer insert adjustable', 'flatware organizer drawer bamboo', 'kitchen cutlery drawer tray'], maxPrice: 30, must: [/cutlery|flatware|drawer/i], prefer: [/cutlery|flatware|drawer.?tray/i], exclude: [/cutlery.?set.?knives/i] },
  { rank: 6, label: 'Office Drawer Organizer', queries: ['desk drawer organizer trays office', 'office supply drawer organizer', 'pen drawer organizer tray set'], maxPrice: 25, must: [/drawer|desk|office/i], prefer: [/desk.?drawer|office.?drawer|pen.?organizer/i], exclude: [/filing.?cabinet.?full/i] },
  { rank: 7, label: 'Bamboo Organizer', queries: ['bamboo drawer organizer kitchen adjustable', 'bamboo drawer dividers expandable', 'bamboo kitchen drawer organizer set'], maxPrice: 35, must: [/bamboo|drawer/i], prefer: [/bamboo.?drawer|bamboo.?organizer/i], exclude: [/bamboo.?cutting.?board.?only/i] },
  { rank: 8, label: 'Deep Drawer Bin', queries: ['deep drawer organizer bins stackable', 'large drawer storage bins kitchen', 'deep kitchen drawer organizer'], maxPrice: 30, must: [/drawer|bin|deep/i], prefer: [/deep.?drawer|drawer.?bin|stackable/i], exclude: [/under.?bed.?storage.?only/i] },
  { rank: 9, label: 'Knife Drawer Insert', queries: ['in drawer knife block organizer', 'knife drawer insert bamboo', 'kitchen knife drawer organizer slot'], maxPrice: 35, must: [/knife|drawer/i], prefer: [/knife.?drawer|drawer.?knife|knife.?block.?insert/i], exclude: [/knife.?set.?block.?countertop/i] },
  { rank: 10, label: 'Non-Slip Mat Liner', queries: ['drawer liner non slip grip mat', 'shelf liner drawer non adhesive grip', 'drawer mat liner cut to fit'], maxPrice: 20, must: [/liner|mat/i], prefer: [/drawer.?liner|non.?slip|grip.?mat/i], exclude: [/contact.?paper.?decor.?only/i] },
]);
