import { pinSlots } from './_pin-lib.mjs';

await pinSlots('picnic', [
  { rank: 1, label: 'Picnic Blanket', queries: ['picnic blanket waterproof foldable', 'outdoor picnic blanket sand proof', 'large picnic blanket with carrying strap'], maxPrice: 40, must: [/picnic.?blanket|outdoor.?blanket/i], prefer: [/waterproof|picnic|foldable/i], exclude: [/electric|weighted.?bed/i] },
  { rank: 2, label: 'Cooler Bag', queries: ['soft cooler bag picnic insulated', 'picnic cooler bag leak proof', 'insulated cooler tote picnic'], maxPrice: 40, must: [/cooler/i], prefer: [/cooler.?bag|insulated|picnic/i], exclude: [/hard.?cooler.?wheel/i] },
  { rank: 3, label: 'Picnic Backpack', queries: ['picnic backpack with utensils plates', 'picnic bag set for 4', 'picnic backpack cooler compartments'], maxPrice: 60, must: [/picnic/i], prefer: [/picnic.?backpack|picnic.?set|for.?4|for.?2/i], exclude: [/hiking.?backpack.?only/i] },
  { rank: 4, label: 'Reusable Plates', queries: ['reusable plastic picnic plates set', 'wheat straw picnic dinnerware set', 'unbreakable picnic plates bowls'], maxPrice: 30, must: [/plate|dinnerware|dish/i], prefer: [/picnic|reusable|unbreakable|wheat.?straw/i], exclude: [/paper.?plate.?disposable/i] },
  { rank: 5, label: 'Wine Tumblers', queries: ['stainless wine tumbler with lid 2 pack', 'insulated wine tumbler picnic', 'stemless wine tumbler set'], maxPrice: 30, must: [/wine.?tumbler|wine.?glass/i], prefer: [/tumbler|insulated|lid|wine/i], exclude: [/wine.?rack|opener.?only/i] },
  { rank: 6, label: 'Cutting Board Set', queries: ['portable cutting board picnic plastic', 'flexible cutting boards set colorful', 'travel cutting board for picnic'], maxPrice: 20, must: [/cutting.?board/i], prefer: [/cutting.?board|flexible|set/i], exclude: [/huge.?butcher.?block/i] },
  { rank: 7, label: 'Bug Repellent', queries: ['picaridin insect repellent spray', 'OFF Deep Woods insect repellent', 'mosquito repellent spray picnic'], maxPrice: 15, must: [/repellent|mosquito|insect/i], prefer: [/repellent|picaridin|mosquito/i], exclude: [/candle.?only|trap.?electric/i] },
  { rank: 8, label: 'Portable Speaker', queries: ['portable bluetooth speaker waterproof small', 'JBL Go bluetooth speaker', 'mini waterproof bluetooth speaker picnic'], maxPrice: 50, must: [/speaker|bluetooth/i], prefer: [/portable|bluetooth.?speaker|waterproof/i], exclude: [/soundbar|party.?box.?huge/i] },
  { rank: 9, label: 'Trash Bags', queries: ['compostable trash bags small picnic', 'small garbage bags for outdoor', 'biodegradable trash bags 4 gallon'], maxPrice: 20, must: [/trash.?bag|garbage.?bag/i], prefer: [/trash.?bag|compostable|small/i], exclude: [/13.?gallon.?kitchen.?only/i] },
  { rank: 10, label: 'Citronella Candle', queries: ['citronella candle outdoor large', 'citronella bucket candle patio', 'mosquito citronella candle outdoor'], maxPrice: 25, must: [/citronella|candle/i], prefer: [/citronella|outdoor|mosquito/i], exclude: [/birthday.?candle|taper/i] },
]);
